'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { Provider } from "../components/ui/provider";
import AppBar from "../components/AppBar";
import Sidebar from "../components/Sidebar";
import React from "react";
import { Flex, Box } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <Flex>
            <Sidebar />
            <Box flex="1" minH="100vh" bg="gray.50">
              <AppBar onOpen={() => {}} />
              <Box as="main" p={6}>
                {children}
              </Box>
            </Box>
          </Flex>
        </Provider>
      </body>
    </html>
  );
}
